
export const dashboardTexts = {
  fr: {
    appName: "Dealtock",
    title: "Dealtock",
    subtitle: "Gestion de produits",
    description: "Connectez-vous à votre espace client sécurisé",
    registrationDescription: "Créez votre compte Dealtock",
    emailPlaceholder: "Adresse email",
    passwordPlaceholder: "Mot de passe",
    loginButton: "Se connecter",
    registerButton: "Créer un compte",
    loadingButton: "Connexion...",
    registeringButton: "Création...",
    demoHint: "Démo : utilisez n'importe quelle adresse email",
    createNewAccount: "Créer un nouveau compte",
    alreadyHaveAccount: "Vous avez déjà un compte ? Se connecter",
    errorFillFields: "Veuillez remplir tous les champs",
    errorLoginFailed: "Erreur de connexion",
    errorRegistrationFailed: "Erreur d'inscription",
    errorCheckCredentials: "Vérifiez vos identifiants",
    errorInvalidPassword: "Le mot de passe ne respecte pas les critères.",
    errorRegistrationGeneric: "Une erreur est survenue lors de l'inscription.",
    successLogin: "Connexion réussie !",
    successWelcome: "Bienvenue dans votre espace client",
    successRegistrationTitle: "Inscription réussie !",
    successRegistrationMessage: "Un email de confirmation a été (simulé) envoyé. Veuillez vérifier votre boîte de réception.",
    passwordErrorMinLength: (length) => `Au moins ${length} caractères`,
    passwordErrorUppercase: "Au moins une majuscule",
    passwordErrorLowercase: "Au moins une minuscule",
    passwordErrorNumber: "Au moins un chiffre",
    passwordErrorSpecialChar: "Au moins un caractère spécial",
    hello: "Bonjour",
    welcomeMessage: "Voici un aperçu de vos produits stockés chez Dealtock.",
    welcomeMessageAdmin: "Bienvenue sur le tableau de bord d'administration de Dealtock.",
    totalProducts: "Total Produits",
    available: "Disponible",
    sold: "Vendu",
    shipped: "Expédié",
    pending_approval: "En attente",
    out_of_stock: "En rupture",
    totalValue: "Valeur en Stock",
    totalSoldAmount: "Total Ventes",
    totalCommission: "Total Commissions",
    totalNetToReceive: "Net à Recevoir",
    allProducts: "Tous les produits",
    actions: "Actions",
    markAsSold: "Marquer comme vendu",
    markAsShipped: "Marquer comme expédié",
    markAsAvailable: "Remettre disponible",
    location: "Emplacement",
    entryDate: "Stocké le",
    saleDate: "Vendu le",
    shippingDate: "Expédié le",
    carrier: "Transporteur",
    trackingLink: "Lien de suivi",
    deliveryProof: "Preuve de livraison",
    value: "Valeur",
    salePrice: "Prix de vente",
    commission: "Commission (10%)",
    netAmount: "Montant net",
    noProductsFound: "Aucun produit trouvé",
    noProductsMatchFilters: "Aucun produit ne correspond aux filtres sélectionnés.",
    profile: "Profil",
    settings: "Paramètres",
    language: "Langue",
    logout: "Déconnexion",
    loadingProducts: "Chargement de vos produits...",
    updatePassword: "Modifier mot de passe",
    enterSalePrice: "Entrer le prix de vente",
    enterShippingInfo: "Entrer les informations d'expédition",
    product: "Produit",
    cancel: "Annuler",
    confirm: "Confirmer",
    viewProof: "Voir la preuve",
    statusUpdateSuccessTitle: "Statut mis à jour",
    statusUpdateSuccessDescription: "Le statut du produit a été modifié avec succès.",
    errorTitle: "Erreur",
    errorEnterSalePrice: "Veuillez entrer un prix de vente.",
    errorEnterCarrier: "Veuillez entrer le nom du transporteur.",
    adminDashboardTitle: "Tableau de Bord Admin",
    managementTasks: "Tâches de Gestion",
    approveNewProductSubmissions: "Approuver Soumissions Produits",
    approveNewProductSubmissionsDesc: "Valider ou refuser les nouveaux produits soumis par les utilisateurs.",
    approveNewUserRegistrations: "Approuver Inscriptions Utilisateurs",
    approveNewUserRegistrationsDesc: "Gérer et valider les demandes d'inscription des nouveaux utilisateurs.",
    userManagement: "Gestion Utilisateurs",
    resetUserPassword: "Réinitialiser Mot de Passe Utilisateur",
    resetUserPasswordDesc: "Rechercher un utilisateur par email et réinitialiser son mot de passe.",
    addNewAdmin: "Ajouter Admin/Modérateur",
    addNewAdminDesc: "Créer un nouveau compte avec des droits d'administration.",
    analyticalDashboard: "Tableau de Bord Analytique",
    topPerformingProducts: "Produits Plus Performants",
    topPerformingProductsDesc: "Visualiser les produits avec le plus de ventes ou d'expéditions.",
    lowPerformingProducts: "Produits Moins Performants",
    lowPerformingProductsDesc: "Identifier les produits en stock depuis plus de 60 jours.",
    overallPlatformStats: "Statistiques Globales",
    overallPlatformStatsDesc: "Accéder aux chiffres clés : ventes, commissions, délais de livraison.",
    userListAndCounters: "Comptes Utilisateurs",
    userListAndCountersDesc: "Voir la liste des utilisateurs et les compteurs.",
    featureNotImplemented: "🚧 Cette fonctionnalité n'est pas encore implémentée—mais ne vous inquiétez pas ! Vous pouvez la demander dans votre prochaine requête ! 🚀",
    addNewProduct: "Ajouter un produit",
    addNewProductDesc: "Soumettre un nouveau produit pour validation par l'administrateur.",
    productName: "Nom du produit",
    productCategory: "Catégorie",
    productValue: "Valeur (MAD)",
    productLocation: "Emplacement dans l'entrepôt",
    productDescription: "Description courte",
    submitForApproval: "Soumettre pour approbation",
    productSubmissionSuccessTitle: "Produit soumis",
    productSubmissionSuccessDesc: "Votre produit a été soumis et est en attente de validation par un administrateur.",
    productSubmissionErrorTitle: "Erreur de soumission",
    productSubmissionErrorDesc: "Veuillez remplir tous les champs du produit.",
    dropshipperStore: "Boutique Dropshipper",
  },
  en: {
    appName: "Dealtock",
    title: "Dealtock",
    subtitle: "Product Management",
    description: "Log in to your secure client area",
    registrationDescription: "Create your Dealtock account",
    emailPlaceholder: "Email address",
    passwordPlaceholder: "Password",
    loginButton: "Log in",
    registerButton: "Create Account",
    loadingButton: "Logging in...",
    registeringButton: "Creating...",
    demoHint: "Demo: use any email address",
    createNewAccount: "Create a new account",
    alreadyHaveAccount: "Already have an account? Log in",
    errorFillFields: "Please fill in all fields",
    errorLoginFailed: "Login failed",
    errorRegistrationFailed: "Registration failed",
    errorCheckCredentials: "Check your credentials",
    errorInvalidPassword: "Password does not meet criteria.",
    errorRegistrationGeneric: "An error occurred during registration.",
    successLogin: "Login successful!",
    successWelcome: "Welcome to your client area",
    successRegistrationTitle: "Registration successful!",
    successRegistrationMessage: "A confirmation email has been (simulated) sent. Please check your inbox.",
    passwordErrorMinLength: (length) => `At least ${length} characters`,
    passwordErrorUppercase: "At least one uppercase letter",
    passwordErrorLowercase: "At least one lowercase letter",
    passwordErrorNumber: "At least one number",
    passwordErrorSpecialChar: "At least one special character",
    hello: "Hello",
    welcomeMessage: "Here is an overview of your products stored at Dealtock.",
    welcomeMessageAdmin: "Welcome to the administration dashboard for Dealtock.",
    totalProducts: "Total Products",
    available: "Available",
    sold: "Sold",
    shipped: "Shipped",
    pending_approval: "Pending",
    out_of_stock: "Out of Stock",
    totalValue: "Stock Value",
    totalSoldAmount: "Total Sales",
    totalCommission: "Total Commissions",
    totalNetToReceive: "Net to Receive",
    allProducts: "All products",
    actions: "Actions",
    markAsSold: "Mark as sold",
    markAsShipped: "Mark as shipped",
    markAsAvailable: "Mark as available",
    location: "Location",
    entryDate: "Stocked on",
    saleDate: "Sold on",
    shippingDate: "Shipped on",
    carrier: "Carrier",
    trackingLink: "Tracking link",
    deliveryProof: "Delivery proof",
    value: "Value",
    salePrice: "Sale price",
    commission: "Commission (10%)",
    netAmount: "Net amount",
    noProductsFound: "No products found",
    noProductsMatchFilters: "No products match the selected filters.",
    profile: "Profile",
    settings: "Settings",
    language: "Language",
    logout: "Logout",
    loadingProducts: "Loading your products...",
    updatePassword: "Update Password",
    enterSalePrice: "Enter sale price",
    enterShippingInfo: "Enter shipping information",
    product: "Product",
    cancel: "Cancel",
    confirm: "Confirm",
    viewProof: "View Proof",
    statusUpdateSuccessTitle: "Status Updated",
    statusUpdateSuccessDescription: "The product status has been successfully updated.",
    errorTitle: "Error",
    errorEnterSalePrice: "Please enter a sale price.",
    errorEnterCarrier: "Please enter the carrier name.",
    adminDashboardTitle: "Admin Dashboard",
    managementTasks: "Management Tasks",
    approveNewProductSubmissions: "Approve Product Submissions",
    approveNewProductSubmissionsDesc: "Validate or decline new products submitted by users.",
    approveNewUserRegistrations: "Approve User Registrations",
    approveNewUserRegistrationsDesc: "Manage and validate new user registration requests.",
    userManagement: "User Management",
    resetUserPassword: "Reset User Password",
    resetUserPasswordDesc: "Search user by email and reset their password.",
    addNewAdmin: "Add Admin/Moderator",
    addNewAdminDesc: "Create a new account with admin privileges.",
    analyticalDashboard: "Analytical Dashboard",
    topPerformingProducts: "Top Performing Products",
    topPerformingProductsDesc: "View products with the most sales or shipments.",
    lowPerformingProducts: "Low Performing Products",
    lowPerformingProductsDesc: "Identify products in stock for more than 60 days.",
    overallPlatformStats: "Overall Platform Stats",
    overallPlatformStatsDesc: "Access key figures: sales, commissions, delivery times.",
    userListAndCounters: "User Accounts",
    userListAndCountersDesc: "View user list and counters.",
    featureNotImplemented: "🚧 This feature isn't implemented yet—but don't worry! You can request it in your next prompt! 🚀",
    addNewProduct: "Add a new product",
    addNewProductDesc: "Submit a new product for admin approval.",
    productName: "Product name",
    productCategory: "Category",
    productValue: "Value (MAD)",
    productLocation: "Warehouse location",
    productDescription: "Short description",
    submitForApproval: "Submit for Approval",
    productSubmissionSuccessTitle: "Product Submitted",
    productSubmissionSuccessDesc: "Your product has been submitted and is awaiting admin approval.",
    productSubmissionErrorTitle: "Submission Error",
    productSubmissionErrorDesc: "Please fill all product fields.",
    dropshipperStore: "Dropshipper Store",
  },
  ar: {
    appName: "ديلتوك",
    title: "ديلتوك",
    subtitle: "إدارة المنتجات",
    description: "سجل الدخول إلى منطقة العميل الآمنة الخاصة بك",
    registrationDescription: "أنشئ حساب ديلتوك الخاص بك",
    emailPlaceholder: "البريد الإلكتروني",
    passwordPlaceholder: "كلمة المرور",
    loginButton: "تسجيل الدخول",
    registerButton: "إنشاء حساب",
    loadingButton: "جاري تسجيل الدخول...",
    registeringButton: "جاري الإنشاء...",
    demoHint: "تجريبي: استخدم أي عنوان بريد إلكتروني",
    createNewAccount: "إنشاء حساب جديد",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟ تسجيل الدخول",
    errorFillFields: "يرجى ملء جميع الحقول",
    errorLoginFailed: "فشل تسجيل الدخول",
    errorRegistrationFailed: "فشل التسجيل",
    errorCheckCredentials: "تحقق من بيانات الاعتماد الخاصة بك",
    errorInvalidPassword: "كلمة المرور لا تستوفي المعايير.",
    errorRegistrationGeneric: "حدث خطأ أثناء التسجيل.",
    successLogin: "تم تسجيل الدخول بنجاح!",
    successWelcome: "مرحباً بك في منطقة العميل الخاصة بك",
    successRegistrationTitle: "تم التسجيل بنجاح!",
    successRegistrationMessage: "تم إرسال بريد إلكتروني للتأكيد (محاكاة). يرجى التحقق من صندوق الوارد الخاص بك.",
    passwordErrorMinLength: (length) => `على الأقل ${length} أحرف`,
    passwordErrorUppercase: "حرف كبير واحد على الأقل",
    passwordErrorLowercase: "حرف صغير واحد على الأقل",
    passwordErrorNumber: "رقم واحد على الأقل",
    passwordErrorSpecialChar: "حرف خاص واحد على الأقل",
    hello: "مرحباً",
    welcomeMessage: "إليك نظرة عامة على منتجاتك المخزنة في ديلتوك.",
    welcomeMessageAdmin: "مرحباً بك في لوحة تحكم الإدارة لـ ديلتوك.",
    totalProducts: "إجمالي المنتجات",
    available: "متوفر",
    sold: "مباع",
    shipped: "تم الشحن",
    pending_approval: "قيد الإنتظار",
    out_of_stock: "نفد المخزون",
    totalValue: "قيمة المخزون",
    totalSoldAmount: "إجمالي المبيعات",
    totalCommission: "إجمالي العمولات",
    totalNetToReceive: "صافي التحصيل",
    allProducts: "جميع المنتجات",
    actions: "الإجراءات",
    markAsSold: "وضع علامة كمباع",
    markAsShipped: "وضع علامة كتم الشحن",
    markAsAvailable: "إعادة للتوفر",
    location: "الموقع",
    entryDate: "خُزّن في",
    saleDate: "بِيع في",
    shippingDate: "شُحِن في",
    carrier: "شركة النقل",
    trackingLink: "رابط التتبع",
    deliveryProof: "إثبات التسليم",
    value: "القيمة",
    salePrice: "سعر البيع",
    commission: "العمولة (10%)",
    netAmount: "المبلغ الصافي",
    noProductsFound: "لم يتم العثور على منتجات",
    noProductsMatchFilters: "لا توجد منتجات تطابق الفلاتر المحددة.",
    profile: "الملف الشخصي",
    settings: "الإعدادات",
    language: "اللغة",
    logout: "تسجيل الخروج",
    loadingProducts: "جاري تحميل منتجاتك...",
    updatePassword: "تحديث كلمة المرور",
    enterSalePrice: "أدخل سعر البيع",
    enterShippingInfo: "أدخل معلومات الشحن",
    product: "المنتج",
    cancel: "إلغاء",
    confirm: "تأكيد",
    viewProof: "عرض الإثبات",
    statusUpdateSuccessTitle: "تم تحديث الحالة",
    statusUpdateSuccessDescription: "تم تحديث حالة المنتج بنجاح.",
    errorTitle: "خطأ",
    errorEnterSalePrice: "الرجاء إدخال سعر البيع.",
    errorEnterCarrier: "الرجاء إدخال اسم شركة النقل.",
    adminDashboardTitle: "لوحة تحكم المسؤول",
    managementTasks: "مهام الإدارة",
    approveNewProductSubmissions: "الموافقة على تقديمات المنتجات",
    approveNewProductSubmissionsDesc: "التحقق من صحة أو رفض المنتجات الجديدة المقدمة من المستخدمين.",
    approveNewUserRegistrations: "الموافقة على تسجيلات المستخدمين",
    approveNewUserRegistrationsDesc: "إدارة طلبات تسجيل المستخدمين الجدد والتحقق منها.",
    userManagement: "إدارة المستخدمين",
    resetUserPassword: "إعادة تعيين كلمة مرور المستخدم",
    resetUserPasswordDesc: "البحث عن مستخدم عن طريق البريد الإلكتروني وإعادة تعيين كلمة المرور الخاصة به.",
    addNewAdmin: "إضافة مسؤول/مشرف جديد",
    addNewAdminDesc: "إنشاء حساب جديد بصلاحيات إدارية.",
    analyticalDashboard: "لوحة التحكم التحليلية",
    topPerformingProducts: "المنتجات الأفضل أداءً",
    topPerformingProductsDesc: "عرض المنتجات التي حققت أكبر عدد من المبيعات أو الشحنات.",
    lowPerformingProducts: "المنتجات الأقل أداءً",
    lowPerformingProductsDesc: "تحديد المنتجات الموجودة في المخزون لأكثر من 60 يومًا.",
    overallPlatformStats: "الإحصائيات العامة للمنصة",
    overallPlatformStatsDesc: "الوصول إلى الأرقام الرئيسية: المبيعات، العمولات، أوقات التسليم.",
    userListAndCounters: "حسابات المستخدمين",
    userListAndCountersDesc: "عرض قائمة المستخدمين والعدادات.",
    featureNotImplemented: "🚧 هذه الميزة لم تنفذ بعد - ولكن لا تقلق! يمكنك طلبها في رسالتك القادمة! 🚀",
    addNewProduct: "إضافة منتج جديد",
    addNewProductDesc: "إرسال منتج جديد لموافقة المسؤول.",
    productName: "اسم المنتج",
    productCategory: "الفئة",
    productValue: "القيمة (د.م.)",
    productLocation: "الموقع في المستودع",
    productDescription: "وصف قصير",
    submitForApproval: "إرسال للموافقة",
    productSubmissionSuccessTitle: "تم إرسال المنتج",
    productSubmissionSuccessDesc: "تم إرسال منتجك وهو في انتظار موافقة المسؤول.",
    productSubmissionErrorTitle: "خطأ في الإرسال",
    productSubmissionErrorDesc: "يرجى ملء جميع حقول المنتج.",
    dropshipperStore: "متجر دروبشيبر",
  }
};
